language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run build
  - npm run test-once
after_script:
  - cat ./coverage/PhantomJS*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
after_success:
  - npm install -g firebase-tools
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]];
    then firebase deploy; fi
env:
  global:
  - secure: UfipS1SGuQHF9nAl31k5oA2pIkPJGXdOyuoVbUw0XsWF2jKd6WBS/qevjOOdL0vsbPdfnng0beKb066mVWvXiwSAN5qSvM+cBsnJa9ctQz1NsMR8KdVyEdVe7VrkbB6pvIqSFvp0QA5LgsPw6KctwrNh3xvNYPdPlSFPWBWXnwQ=
  - secure: CfTfhCFsOsATjYrV1JuZ+G2X/TxunmD533icNvKW8kmUINX5hRq+mwlPElsTf7J9mEVxWDwA6erdjrUO6Gr5wfH3ieYegb+5YQAcE5ltaSqKTZtXGkCReOPz3/ZUvmQox643goTyg1MgB7vvEC/PDKcyPfmFM3meTqrAooj7GKQ=
  - secure: GmIMQxFUee2AD5cFyL0jLHLsgQjU9DmbNCLrH+BjocSRpwHDW/jVa189MjTuFZ913f3Qyr+A/O1ik5mhSrZuOXt0LODZiJOBfP++jqQ4IKq4REJsvfsiW6gb+yAGWTm8B/cKBirQ/mjn8aQBrpnREkh6SBqZjSPM8B4AsamjRfU=
  - secure: ea/ynj7K0WY1wySvnjFrG294AvZMdjxPRDDScYwBC4h/vw/oBn8X5qf4gREk4tjrqVaZ6xwlmY2BR1cNMTCeOxOj+67XjLdRAQLTPsVfW3ZeRb4NTtmTBymWIM1OdzIWExzsX9N2fJgzLfB4TmWv4XVKnbrsYN9F2Q3Gv3sDaU4=
